#!/usr/bin/env bash
set -e

function get_user_gpg_keys() {
	local USER="$1"
	local TEMPLATE="{{ range . }}{{ printf \"%s\\n\" .raw_key }}{{ end }}"

	echo "Importing GPG keys for user:  $USER"
	gh api "users/$USER/gpg_keys" --paginate --template="${TEMPLATE}" | gpg --import
}

ORGANIZATION=
TEAM=
USER=

__USAGE="
Import GPG keys from GitHub users.

USAGE
  $(basename $0) [options] <organization>/<team>
  $(basename $0) [options] <user>

FLAGS
  -d, --debug                         Enable debugging
";

die() {
	printf "\nError: %s\n" "$1"
	echo "$__USAGE"
	exit 1
}

if ! type -p gh > /dev/null; then
	die "'gh' could not be found"
fi

while getopts "dh:-:" OPT; do
	if [ "$OPT" = "-" ]; then    # long option: reformulate OPT and OPTARG
		OPT="${OPTARG%%=*}"      # extract long option name
		OPTARG="${OPTARG#$OPT}"	 # extract long option argument (may be empty)
		OPTARG="${OPTARG#=}"     # if long option argument, remove assigning `=`
	fi

	case "$OPT" in

		debug | d)
			set -x
			;;

		help | h)
			echo "$__USAGE"
			exit 0
			;;
	esac
done

# shift so that $@, $1, etc. refer to the non-option arguments
shift "$((OPTIND-1))"

if [ -z "$1" ]; then
	die "Must provide organization/team or user"
elif [[ "$1" == *"/"* ]]; then
	ORGANIZATION=$(echo $1 | cut -d '/' -f 1)
	TEAM=$(echo $1 | cut -d '/' -f 2)
else
	USER="$1"
fi

if [ -z "${USER}" ]; then
	QUERY='
	query ($login: String!, $slug: String!, $endCursor: String) {
	  organization(login: $login) {
		team(slug: $slug) {
		  members(first: 10, after: $endCursor, membership: ALL) {
			pageInfo {
			  endCursor
			  hasNextPage
			}
			nodes {
			  login
			}
		  }
		}
	  }
	}'

	echo "Pulling GPG keys for team:  $ORGANIZATION/$TEAM"

	for user in $(gh api graphql -f query="${QUERY}" -F login="$ORGANIZATION" -F slug="$TEAM" --paginate --jq '.data.organization.team.members.nodes[].login'); do
		get_user_gpg_keys "${user}"
	done
elif [ "${USER}" = "GitHub" ]; then
	echo "Importing GPG keys for GitHub web commits"
	curl -s https://github.com/web-flow.gpg | gpg --import
else
	get_user_gpg_keys "${USER}"
fi
